/**
 * A 64-square board in two 32-bit halves.
 *
 * The Python engine keeps a board in one integer, one bit per square, and moves
 * every disc at once with a shift. That does not survive the trip to
 * JavaScript: ordinary numbers here are doubles, exact only up to 2^53, so the
 * top eleven squares of an 8x8 board cannot be held in one. (This is the same
 * hazard the HTTP API works around by sending boards as hex strings rather than
 * JSON numbers.)
 *
 * `BigInt` would port the Python line for line, but it allocates on every
 * operation and this code runs inside a tree search that touches it millions of
 * times per move. So a board is two 32-bit halves, `lo` for squares 0-31 and
 * `hi` for squares 32-63, and a shift becomes a pair of shifts plus a carry
 * across the seam between them.
 *
 * That seam is the whole risk. A carry that is wrong in one direction out of
 * eight produces a board that looks entirely normal and plays a different game.
 * It is checked against 1,000 positions generated by the frozen Python engine,
 * including the exact set of discs every legal move flips -- see
 * `tests/rules.test.ts`.
 *
 * Contract C1 throughout: bit `i` is row `i / size`, column `i % size`, row 0
 * at the top and column 0 at the left. The same mapping as the engine, the
 * feature encoder, the API and the board on screen.
 */

/** A board, as two unsigned 32-bit halves. Treat as immutable. */
export interface Bits {
  readonly lo: number;
  readonly hi: number;
}

export const EMPTY: Bits = { lo: 0, hi: 0 };

/** Squares 0-31 live in `lo`, squares 32-63 in `hi`. */
export function bit(index: number): Bits {
  return index < 32
    ? { lo: (1 << index) >>> 0, hi: 0 }
    : { lo: 0, hi: (1 << (index - 32)) >>> 0 };
}

export function isEmpty(b: Bits): boolean {
  return b.lo === 0 && b.hi === 0;
}

export function equals(a: Bits, b: Bits): boolean {
  return a.lo === b.lo && a.hi === b.hi;
}

export function or(a: Bits, b: Bits): Bits {
  return { lo: (a.lo | b.lo) >>> 0, hi: (a.hi | b.hi) >>> 0 };
}

export function and(a: Bits, b: Bits): Bits {
  return { lo: (a.lo & b.lo) >>> 0, hi: (a.hi & b.hi) >>> 0 };
}

export function xor(a: Bits, b: Bits): Bits {
  return { lo: (a.lo ^ b.lo) >>> 0, hi: (a.hi ^ b.hi) >>> 0 };
}

export function andNot(a: Bits, b: Bits): Bits {
  return { lo: (a.lo & ~b.lo) >>> 0, hi: (a.hi & ~b.hi) >>> 0 };
}

export function testBit(b: Bits, index: number): boolean {
  return index < 32
    ? ((b.lo >>> index) & 1) === 1
    : ((b.hi >>> (index - 32)) & 1) === 1;
}

/**
 * How many discs.
 *
 * The standard SWAR popcount: add bits in pairs, then nibbles, then bytes, and
 * read the total out of the top byte. `Math.imul` rather than `*` because the
 * final multiply overflows 32 bits, and `*` would quietly promote it to a
 * double and lose the low bits that carry the answer.
 */
function popcount32(x: number): number {
  x = x - ((x >>> 1) & 0x55555555);
  x = (x & 0x33333333) + ((x >>> 2) & 0x33333333);
  x = (x + (x >>> 4)) & 0x0f0f0f0f;
  return (Math.imul(x, 0x01010101) >>> 24) & 0x3f;
}

export function popcount(b: Bits): number {
  return popcount32(b.lo) + popcount32(b.hi);
}

/** Which squares are set, ascending. Loops once per disc, not once per square. */
export function indices(b: Bits): number[] {
  const out: number[] = [];
  let lo = b.lo;
  while (lo !== 0) {
    const lowest = lo & -lo;
    out.push(31 - Math.clz32(lowest));
    lo = (lo ^ lowest) >>> 0;
  }
  let hi = b.hi;
  while (hi !== 0) {
    const lowest = hi & -hi;
    out.push(63 - Math.clz32(lowest));
    hi = (hi ^ lowest) >>> 0;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Shifting across the 32-bit seam
// ---------------------------------------------------------------------------

/**
 * Move every disc `n` squares towards higher indices.
 *
 * `n` must be between 1 and 31. JavaScript takes shift counts modulo 32, so
 * `x << 32` is `x` and `x >>> 32` is `x` -- a shift of exactly 32 would
 * silently do nothing rather than clearing the value, and `32 - n` inside the
 * carry would do the same. Every direction on a 4x4, 6x6 or 8x8 board shifts by
 * 1, size-1, size or size+1, so the range always holds; `geometry` checks it
 * once rather than trusting it here.
 */
function shiftLeft(lo: number, hi: number, n: number): Bits {
  return {
    lo: (lo << n) >>> 0,
    hi: ((hi << n) | (lo >>> (32 - n))) >>> 0,
  };
}

/** Move every disc `n` squares towards lower indices. Same range rule. */
function shiftRight(lo: number, hi: number, n: number): Bits {
  return {
    lo: ((lo >>> n) | (hi << (32 - n))) >>> 0,
    hi: hi >>> n,
  };
}

/**
 * One direction, precomputed as "drop these discs, then move this far".
 *
 * `guard` is the set of squares allowed to make this move. Squares are numbered
 * in reading order, so the square to the right of the last column is the first
 * column of the *next row* -- numerically next door, nowhere near it on the
 * board. A disc already against that edge is cleared before the shift rather
 * than being teleported across it.
 */
export interface Shift {
  readonly dRow: number;
  readonly dCol: number;
  readonly delta: number;
  readonly guard: Bits;
}

export interface Geometry {
  readonly size: number;
  readonly nSquares: number;
  readonly full: Bits;
  readonly shifts: readonly Shift[];
}

/** The eight directions, in the same order as the Python engine. */
const DIRECTIONS: ReadonlyArray<readonly [number, number]> = [
  [-1, -1],
  [-1, 0],
  [-1, 1],
  [0, -1],
  [0, 1],
  [1, -1],
  [1, 0],
  [1, 1],
];

const GEOMETRIES = new Map<number, Geometry>();

export function geometry(size: number): Geometry {
  const cached = GEOMETRIES.get(size);
  if (cached !== undefined) return cached;

  if (size < 4 || size % 2 !== 0 || size > 8) {
    throw new Error(`board size must be even and between 4 and 8, got ${size}`);
  }

  const nSquares = size * size;
  const full = maskOfSquares(nSquares);

  let notLastCol = full;
  let notFirstCol = full;
  for (let row = 0; row < size; row++) {
    notLastCol = andNot(notLastCol, bit(row * size + size - 1));
    notFirstCol = andNot(notFirstCol, bit(row * size));
  }

  const shifts: Shift[] = DIRECTIONS.map(([dRow, dCol]) => {
    const delta = dRow * size + dCol;
    if (Math.abs(delta) < 1 || Math.abs(delta) > 31) {
      throw new Error(`shift of ${delta} is outside the range this code can express`);
    }
    return {
      dRow,
      dCol,
      delta,
      guard: dCol > 0 ? notLastCol : dCol < 0 ? notFirstCol : full,
    };
  });

  const geo: Geometry = { size, nSquares, full, shifts };
  GEOMETRIES.set(size, geo);
  return geo;
}

/**
 * The low `n` bits set.
 *
 * Both halves special-case a full 32 bits, because JavaScript takes shift
 * counts modulo 32: `1 << 32` is `1`, not 2^32, so the obvious `(1 << n) - 1`
 * silently yields 0 for a full half rather than all ones. On an 8x8 board that
 * is the difference between a 64-square board and a 32-square one, and the
 * engine goes on working -- it just stops believing in the bottom four rows.
 */
function maskOfSquares(n: number): Bits {
  const low = Math.min(n, 32);
  const high = Math.max(n - 32, 0);
  return {
    lo: (low >= 32 ? 0xffffffff : (1 << low) - 1) >>> 0,
    hi: (high >= 32 ? 0xffffffff : (1 << high) - 1) >>> 0,
  };
}

/**
 * Move every disc one square in one direction.
 *
 * Discs leaving sideways are removed by the guard first; discs leaving off the
 * top or bottom fall out when the result is masked back onto the board.
 */
export function shift(b: Bits, step: Shift, full: Bits): Bits {
  const guarded = and(b, step.guard);
  if (step.delta > 0) {
    return and(shiftLeft(guarded.lo, guarded.hi, step.delta), full);
  }
  return shiftRight(guarded.lo, guarded.hi, -step.delta);
}

// ---------------------------------------------------------------------------
// Hex, at the edges only
// ---------------------------------------------------------------------------

/**
 * Parse a board from the hex form the fixtures and the HTTP API both use.
 *
 * Read as two 32-bit halves rather than through `Number` or `BigInt`: this is
 * the exact place where a board would lose its top squares if it were turned
 * into an ordinary number first.
 */
export function fromHex(hex: string): Bits {
  const padded = hex.padStart(16, "0");
  return {
    hi: parseInt(padded.slice(0, 8), 16) >>> 0,
    lo: parseInt(padded.slice(8, 16), 16) >>> 0,
  };
}

export function toHex(b: Bits, digits = 16): string {
  const hex = b.hi.toString(16).padStart(8, "0") + b.lo.toString(16).padStart(8, "0");
  return hex.slice(16 - digits);
}
