/**
 * The rules of Reversi, for the third time.
 *
 * They exist twice already in Python -- an obvious list-of-lists version written
 * as the specification, and the fast bitboard version the agent was trained
 * against -- checked against each other move by move over 50,000 games and then
 * frozen. This file is a port of the fast one, and it is held to the same
 * standard: every expectation it is tested against was generated by that engine
 * rather than written by hand here.
 *
 * That matters because a wrong port does not crash. The browser would play a
 * slightly different game from the one the agent learned, the agent would look
 * weaker than it is, and nothing would say so.
 *
 * Contract C3 is the part most often got wrong, so it is written out plainly:
 *
 *     if I have a placement:            play it;     not terminal
 *     elif my opponent has one:         only PASS;   not terminal
 *     else:                             no actions;  TERMINAL
 *
 * "Two passes in a row" is therefore never a state this code can be in -- it
 * collapses into terminal at the first check. A full board is terminal by the
 * same rule, not by a special case. No pass counter is consulted anywhere.
 */

import {
  and,
  andNot,
  bit,
  EMPTY,
  equals,
  geometry,
  indices,
  isEmpty,
  or,
  popcount,
  shift,
  testBit,
  toHex,
  type Bits,
  type Geometry,
} from "./bitboard";

/** Black moves first. The numbers match the Python `Player` enum. */
export const BLACK = 0;
export const WHITE = 1;
export type Player = typeof BLACK | typeof WHITE;

/** A square index, or `passAction(size)` for PASS. */
export type Action = number;

export interface State {
  readonly black: Bits;
  readonly white: Bits;
  readonly toMove: Player;
  readonly size: number;
}

export class IllegalMoveError extends Error {}

export function passAction(size: number): Action {
  return size * size;
}

export function policySize(size: number): number {
  return size * size + 1;
}

export function opponent(player: Player): Player {
  return player === BLACK ? WHITE : BLACK;
}

/** The mover's own discs. The engine never canonicalises colour into the state. */
export function mine(state: State): Bits {
  return state.toMove === BLACK ? state.black : state.white;
}

export function theirs(state: State): Bits {
  return state.toMove === BLACK ? state.white : state.black;
}

export function occupied(state: State): Bits {
  return or(state.black, state.white);
}

/**
 * The standard opening: four discs in the middle, black to move.
 *
 * White takes the two squares on the leading diagonal and black the other two,
 * which is the arrangement every Reversi program starts from.
 */
export function initialState(size: number): State {
  const half = size / 2;
  const topLeft = (half - 1) * size + (half - 1);
  const topRight = (half - 1) * size + half;
  const bottomLeft = half * size + (half - 1);
  const bottomRight = half * size + half;

  return {
    black: or(bit(topRight), bit(bottomLeft)),
    white: or(bit(topLeft), bit(bottomRight)),
    toMove: BLACK,
    size,
  };
}

// ---------------------------------------------------------------------------
// Legal moves
// ---------------------------------------------------------------------------

/**
 * Every square this player could play, as a bitboard.
 *
 * The trick that makes this fast: instead of asking "is this square legal?"
 * once per square, walk outward from all of my discs at once. In each of the
 * eight directions, repeatedly step one square and keep whatever landed on an
 * opponent disc. Wherever such a run finally meets an empty square, that empty
 * square is a legal move -- it would trap the run between the new disc and the
 * one the run started from.
 */
function placements(own: Bits, other: Bits, geo: Geometry): Bits {
  const empty = andNot(geo.full, or(own, other));
  let moves: Bits = EMPTY;

  for (const step of geo.shifts) {
    // One step out from my discs, keeping only what landed on an opponent.
    let run = and(shift(own, step, geo.full), other);

    // Extend the run while it stays on opponent discs. At most size-1 steps,
    // because that is the longest a run of discs can be.
    for (let i = 0; i < geo.size - 2; i++) {
      run = or(run, and(shift(run, step, geo.full), other));
    }

    moves = or(moves, and(shift(run, step, geo.full), empty));
  }

  return moves;
}

export function legalPlacements(state: State): Bits {
  return placements(mine(state), theirs(state), geometry(state.size));
}

/** What `player` could play, whether or not it is their turn. Used for C3. */
export function legalPlacementsFor(state: State, player: Player): Bits {
  const [own, other] =
    player === BLACK ? [state.black, state.white] : [state.white, state.black];
  return placements(own, other, geometry(state.size));
}

/**
 * The actions available here.
 *
 * Contract C3, exactly. PASS and placements are never legal at the same time,
 * and PASS is never legal at a terminal position.
 */
export function legalActions(state: State): Action[] {
  const own = legalPlacements(state);
  if (!isEmpty(own)) return indices(own);

  if (!isEmpty(legalPlacementsFor(state, opponent(state.toMove)))) {
    return [passAction(state.size)];
  }
  return [];
}

export function isTerminal(state: State): boolean {
  return (
    isEmpty(legalPlacements(state)) &&
    isEmpty(legalPlacementsFor(state, opponent(state.toMove)))
  );
}

export function mustPass(state: State): boolean {
  const legal = legalActions(state);
  return legal.length === 1 && legal[0] === passAction(state.size);
}

// ---------------------------------------------------------------------------
// Flipping
// ---------------------------------------------------------------------------

/**
 * The discs playing `action` would turn over.
 *
 * Per direction: step outward from the square collecting opponent discs, then
 * check whether the next square along holds one of mine. If it does, the whole
 * collected run is trapped and flips. If it does not -- an empty square, or the
 * edge of the board -- this direction contributes nothing.
 */
export function flips(state: State, action: Action): Bits {
  const geo = geometry(state.size);
  if (action === passAction(state.size)) return EMPTY;

  const own = mine(state);
  const other = theirs(state);
  const square = bit(action);
  let flipped: Bits = EMPTY;

  for (const step of geo.shifts) {
    let run: Bits = EMPTY;
    let cursor = and(shift(square, step, geo.full), other);

    while (!isEmpty(cursor)) {
      run = or(run, cursor);
      cursor = and(shift(cursor, step, geo.full), other);
    }

    // The run only flips if it is closed by one of my own discs.
    if (!isEmpty(and(shift(run, step, geo.full), own))) {
      flipped = or(flipped, run);
    }
  }

  return flipped;
}

// ---------------------------------------------------------------------------
// Applying a move
// ---------------------------------------------------------------------------

/**
 * Play `action` and return the position that follows. Never mutates the input.
 *
 * Copying rather than mutating is normally a performance question; here a board
 * is four small numbers, so a copy is cheaper than an undo stack -- and it
 * removes the entire class of bug where a node in the search tree quietly holds
 * a board that something else changed underneath it. Those are the hardest bugs
 * to find in a tree search, so they are bought out at the start.
 */
export function apply(state: State, action: Action): State {
  const size = state.size;
  const pass = passAction(size);

  if (action === pass) {
    if (!isEmpty(legalPlacements(state))) {
      throw new IllegalMoveError(
        `cannot pass at ${describe(state)}: there are legal placements`,
      );
    }
    if (isTerminal(state)) {
      throw new IllegalMoveError(`the game is over at ${describe(state)}`);
    }
    return { ...state, toMove: opponent(state.toMove) };
  }

  if (!Number.isInteger(action) || action < 0 || action >= size * size) {
    throw new IllegalMoveError(`action ${action} is not a square on a ${size}x${size} board`);
  }
  if (testBit(occupied(state), action)) {
    throw new IllegalMoveError(`square ${action} is already occupied at ${describe(state)}`);
  }

  const flipped = flips(state, action);
  if (isEmpty(flipped)) {
    throw new IllegalMoveError(
      `playing ${action} at ${describe(state)} would flip nothing, so it is not legal`,
    );
  }

  const placed = or(bit(action), flipped);
  const own = or(mine(state), placed);
  const other = andNot(theirs(state), flipped);

  return state.toMove === BLACK
    ? { black: own, white: other, toMove: WHITE, size }
    : { black: other, white: own, toMove: BLACK, size };
}

// ---------------------------------------------------------------------------
// Scoring
// ---------------------------------------------------------------------------

export function discCounts(state: State): { black: number; white: number } {
  return { black: popcount(state.black), white: popcount(state.white) };
}

/**
 * The result at a terminal position, from the point of view of the player to
 * move there: +1 win, 0 draw, -1 loss.
 *
 * This is the one perspective convention the whole project uses -- the network,
 * the search backup, the training target and the API all mean the same thing by
 * a value. Empty squares are awarded to nobody.
 */
export function result(state: State): number {
  const { black, white } = discCounts(state);
  const forBlack = Math.sign(black - white);
  return state.toMove === BLACK ? forBlack : -forBlack;
}

export function winner(state: State): "black" | "white" | "draw" {
  const { black, white } = discCounts(state);
  return black > white ? "black" : white > black ? "white" : "draw";
}

// ---------------------------------------------------------------------------

export function describe(state: State): string {
  const digits = Math.ceil((state.size * state.size) / 4);
  return (
    `${toHex(state.black, digits)}/${toHex(state.white, digits)} ` +
    `${state.toMove === BLACK ? "black" : "white"} to move`
  );
}

export function sameState(a: State, b: State): boolean {
  return (
    equals(a.black, b.black) &&
    equals(a.white, b.white) &&
    a.toMove === b.toMove &&
    a.size === b.size
  );
}
