"""The data a TypeScript port of this engine has to reproduce.

The strongest thing about this project is that the rules were *proved* rather
than assumed: two independent implementations, compared move by move over 50,000
random games, zero mismatches, then frozen. Every strength number since rests on
that.

Running the agent in a browser means writing the rules a third time, in
TypeScript. A subtly wrong port would fail in the worst available way -- it would
not crash. The browser would play a slightly different game from the one the
agent was trained on, the agent would look weaker than it is, and nothing would
report a problem.

So the port is held to the same standard, and the expectations are **generated
rather than hand-written**. A hand-written test encodes what somebody believed
the rules were; a generated one encodes what the frozen engine actually does,
which is what the agent was trained against.

Six fixtures, each aimed at a specific way a port goes wrong:

``rules``
    Legal actions, the exact set of discs each move flips, terminal, score. Ports
    fail here on edge wrap-around -- a shift that walks off column H and reappears
    on column A -- and on the pass rule.
``encoding``
    Positions to the three input planes. Catches a transposed board or the wrong
    player's point of view, which would leave the network reading a position that
    does not exist.
``network``
    Positions to the exported network's own outputs. Catches a broken ONNX export
    or wrong input scaling in the browser.
``search``
    Visit counts from a deterministic evaluator with no exploration noise. This
    is the one that catches the value-sign inversion -- the classic silent killer
    -- because a search with a flipped sign still returns a legal move.
``games``
    Whole games played out move by move. Catches anything the per-position
    fixtures let through.
``endgame``
    The exact value of a solved ending, and of every move in it. The browser
    plays the puzzle endings out with its own exact search, so this is a third
    implementation of the same thing -- and a wrong one would not crash, it would
    answer a puzzle with a move that is not best while the page states the result
    as certain.

A seventh file, ``puzzles``, is written from here but is not one of those six
and is not generated by ``write_fixtures``. It is not an expectation a port has to
reproduce -- it is content the app ships, mined by playing games and solving the
endings exactly, which takes minutes and a trained network. ``puzzles_fixture``
says what it is for and why nothing diffs it.

**On the stub evaluator.** The search fixture cannot use the real network,
because two runtimes doing float arithmetic in different orders will not always
break an exact tie the same way, and one different choice early in a tree changes
every count after it. Instead it uses a stand-in whose answers are a plain
integer hash of the position -- reproducible exactly in any language with a
32-bit multiply. That isolates what this fixture is for: the search arithmetic,
not the network.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any

import numpy as np

from reversi.endgame.puzzles import STAGES
from reversi.endgame.solver import empties, solve_exact, solve_root
from reversi.game import rules, scoring
from reversi.game.bitboard import geometry, popcount
from reversi.game.state import State
from reversi.nn.features import encode
from reversi.search.config import SearchConfig
from reversi.search.evaluator import StubEvaluator
from reversi.search.mcts import MCTS
from reversi.types import Player, pass_action, policy_size

if TYPE_CHECKING:
    from numpy.typing import NDArray

    from reversi.endgame.puzzles import Puzzle

__all__ = [
    "FIXTURE_VERSION",
    "STUB_SEED_SALT",
    "encoding_fixture",
    "endgame_fixture",
    "games_fixture",
    "network_fixture",
    "puzzles_fixture",
    "rules_fixture",
    "search_fixture",
    "stub_evaluator",
    "write_fixture_file",
    "write_fixtures",
]

FIXTURE_VERSION = 1

# Mixed into the position hash so the stub's answers are specific to this
# purpose and cannot be confused with any other seeding in the project.
STUB_SEED_SALT = 0x9E3779B9

_U32 = 0xFFFFFFFF


# ---------------------------------------------------------------------------
# The stub evaluator: a network stand-in that any language can reproduce
# ---------------------------------------------------------------------------


def _mix32(x: int) -> int:
    """A 32-bit integer hash (the well-known "lowbias32" mixer).

    Chosen because it ports exactly. Every step is a 32-bit xor, shift or
    multiply, and JavaScript has all three -- the multiply being ``Math.imul``,
    which is defined to be exactly this operation. A hash built from ordinary
    JavaScript arithmetic would overflow into floating point and silently stop
    matching.
    """
    x &= _U32
    x = ((x ^ (x >> 16)) * 0x7FEB352D) & _U32
    x = ((x ^ (x >> 15)) * 0x846CA68B) & _U32
    return (x ^ (x >> 16)) & _U32


def stub_seed(state: State) -> int:
    """A 32-bit fingerprint of a position.

    The board is fed in as four 32-bit halves rather than two 64-bit integers,
    because that is how a JavaScript port has to hold it anyway -- ordinary
    JavaScript numbers stop being exact above 2^53, so a 64-bit board cannot
    survive as one of them.
    """
    seed = STUB_SEED_SALT
    for part in (
        state.black & _U32,
        (state.black >> 32) & _U32,
        state.white & _U32,
        (state.white >> 32) & _U32,
        int(state.to_move),
    ):
        seed = _mix32(seed ^ part)
    return seed


def stub_logit(seed: int, action: int) -> float:
    """One policy logit, in [-2, 2). Division by 2^32 is exact in both languages."""
    return (_mix32(seed ^ (action + 1)) / 4294967296.0) * 4.0 - 2.0


def stub_value(seed: int) -> float:
    """The position's score, in [-1, 1)."""
    return (_mix32(seed ^ 0x5BF03635) / 4294967296.0) * 2.0 - 1.0


def stub_evaluator() -> StubEvaluator:
    """The evaluator the search fixture is generated with.

    Deliberately *opinionated* rather than uniform. A stub that rates every move
    equally makes the search explore in a flat, symmetric way, which would hide a
    prior that was being applied to the wrong action -- the visit counts would
    look plausible either way.
    """

    def policy(state: State) -> NDArray[np.float32]:
        seed = stub_seed(state)
        width = policy_size(state.size)
        return np.array([stub_logit(seed, a) for a in range(width)], dtype=np.float32)

    def value(state: State) -> float:
        return stub_value(stub_seed(state))

    return StubEvaluator(policy=policy, value=value)


# ---------------------------------------------------------------------------
# Sampling positions
# ---------------------------------------------------------------------------


def sample_positions(
    *,
    count: int,
    board_size: int,
    seed: int,
) -> list[State]:
    """Positions drawn from random games, including terminal ones.

    Random play rather than agent play, deliberately. A trained agent visits a
    narrow, sensible slice of the game; the awkward positions where a port breaks
    -- long forced sequences, near-wipeouts, boards where one side must pass
    repeatedly -- are exactly the ones it avoids.
    """
    rng = np.random.default_rng(seed)
    found: list[State] = []
    seen: set[tuple[int, int, int]] = set()

    while len(found) < count:
        state = rules.initial_state(board_size)
        while True:
            key = (state.black, state.white, int(state.to_move))
            if key not in seen:
                seen.add(key)
                found.append(state)
                if len(found) >= count:
                    break
            if rules.is_terminal(state):
                break
            legal = rules.legal_actions(state)
            state = rules.apply(state, int(legal[rng.integers(0, len(legal))]))

    return found[:count]


def _position(state: State) -> list[Any]:
    """A position as the compact triple every fixture keys on."""
    width = (state.size * state.size + 3) // 4
    return [f"{state.black:0{width}x}", f"{state.white:0{width}x}", int(state.to_move)]


# ---------------------------------------------------------------------------
# The fixtures
# ---------------------------------------------------------------------------


def rules_fixture(*, count: int, board_size: int, seed: int) -> dict[str, Any]:
    """Legal actions, flip masks, terminal flag and score for many positions.

    The flip masks are the valuable part. Legal-move generation and flip
    generation share the same eight-direction walk, so a direction that is
    subtly wrong often still produces a plausible-looking legal set while
    flipping the wrong discs.
    """
    cases = []
    for state in sample_positions(count=count, board_size=board_size, seed=seed):
        legal = rules.legal_actions(state)
        black, white = scoring.disc_counts(state)
        cases.append(
            [
                *_position(state),
                list(legal),
                [
                    [int(a), f"{rules.flips(state, a):x}"]
                    for a in legal
                    if a != pass_action(board_size)
                ],
                int(rules.is_terminal(state)),
                black,
                white,
            ]
        )

    return {
        "fixture": "rules",
        "version": FIXTURE_VERSION,
        "board_size": board_size,
        "seed": seed,
        "pass_action": pass_action(board_size),
        "schema": [
            "black_hex",
            "white_hex",
            "to_move",
            "legal_actions",
            "flips_by_action",
            "is_terminal",
            "black_discs",
            "white_discs",
        ],
        "cases": cases,
    }


def encoding_fixture(*, count: int, board_size: int, seed: int) -> dict[str, Any]:
    """Positions to input planes, as bitmasks rather than arrays of floats.

    The planes only ever hold 0.0 or 1.0, so storing them as bitmasks keeps the
    file small *and* keeps the check sharp: it compares the exact square each
    value landed on, which is what contract C1 is about. A transposed board is
    the failure this catches, and it is invisible in a summary statistic.
    """
    cases = []
    width = (board_size * board_size + 3) // 4
    for state in sample_positions(count=count, board_size=board_size, seed=seed):
        planes = encode(state)
        packed = []
        for plane in planes:
            bits = 0
            flat = plane.reshape(-1)
            for index in range(board_size * board_size):
                if flat[index] > 0.5:
                    bits |= 1 << index
            packed.append(f"{bits:0{width}x}")
        cases.append([*_position(state), packed])

    return {
        "fixture": "encoding",
        "version": FIXTURE_VERSION,
        "board_size": board_size,
        "seed": seed,
        "planes": ["mine", "theirs", "my_legal_placements"],
        "note": "plane bit i is row i // size, column i % size (contract C1)",
        "schema": ["black_hex", "white_hex", "to_move", "planes_hex"],
        "cases": cases,
    }


def network_fixture(
    *, count: int, board_size: int, seed: int, onnx_path: Path, decimals: int = 5
) -> dict[str, Any]:
    """What the exported network answers for a set of positions.

    Run through ONNX Runtime rather than PyTorch on purpose: this fixture exists
    to prove the browser and this machine get the same answers from the same
    file, so it should be generated by the same kind of runtime the browser uses.
    """
    import onnxruntime as ort

    from reversi.nn.onnx import run_onnx

    states = sample_positions(count=count, board_size=board_size, seed=seed)
    batch = np.stack([encode(s) for s in states]).astype(np.float32)

    session = ort.InferenceSession(str(onnx_path), providers=["CPUExecutionProvider"])
    policy, value = run_onnx(session, batch)

    cases = [
        [
            *_position(state),
            [round(float(v), decimals) for v in policy[row]],
            round(float(value[row][0]), decimals),
        ]
        for row, state in enumerate(states)
    ]

    return {
        "fixture": "network",
        "version": FIXTURE_VERSION,
        "board_size": board_size,
        "seed": seed,
        "onnx": onnx_path.name,
        "decimals": decimals,
        "tolerance": 10.0**-decimals * 5,
        "schema": ["black_hex", "white_hex", "to_move", "policy_logits", "value"],
        "cases": cases,
    }


def search_fixture(
    *,
    count: int,
    board_size: int,
    seed: int,
    simulations: int = 64,
) -> dict[str, Any]:
    """Visit counts from a search with a reproducible stand-in for the network.

    Exploration noise is off, so the search is fully deterministic: the same
    position and the same evaluator must produce the same tree every time. That
    is what makes an exact comparison meaningful.

    Terminal positions are skipped -- there is no search to run -- and so are
    positions with a single legal action, where the real code skips the search
    entirely anyway.
    """
    evaluator = stub_evaluator()
    config = SearchConfig(n_simulations=simulations, dirichlet_eps=0.0, temp_moves=0)
    config.assert_no_noise("the search fixture")

    cases = []
    for state in sample_positions(count=count * 3, board_size=board_size, seed=seed):
        if rules.is_terminal(state) or len(rules.legal_actions(state)) < 2:
            continue

        result = MCTS(evaluator, config).run(state)
        cases.append(
            [
                *_position(state),
                list(result.actions),
                list(result.visits),
                round(float(result.root_value), 6),
                int(result.best_action()),
            ]
        )
        if len(cases) >= count:
            break

    return {
        "fixture": "search",
        "version": FIXTURE_VERSION,
        "board_size": board_size,
        "seed": seed,
        "simulations": simulations,
        "evaluator": {
            "kind": "hash-stub",
            "salt": STUB_SEED_SALT,
            "note": (
                "logit(a) = mix32(seed ^ (a+1)) / 2^32 * 4 - 2; "
                "value = mix32(seed ^ 0x5BF03635) / 2^32 * 2 - 1; "
                "seed = fold of mix32 over black_lo, black_hi, white_lo, white_hi, to_move"
            ),
        },
        "note": (
            "Exact visit-count agreement requires the port to round its PUCT "
            "arithmetic to float32 the way numpy does (Math.fround in JavaScript). "
            "Without that, compare the chosen move and allow a stated tolerance on "
            "the counts -- and say which was done."
        ),
        "schema": ["black_hex", "white_hex", "to_move", "actions", "visits", "root_value", "best"],
        "cases": cases,
    }


def games_fixture(*, count: int, board_size: int, seed: int) -> dict[str, Any]:
    """Whole games as move lists, with the position after every move.

    Per-position fixtures check each rule in isolation. This one checks that
    applying them in sequence stays in step -- the failure where two engines each
    look right and drift apart anyway.
    """
    rng = np.random.default_rng(seed)
    games = []

    for _ in range(count):
        state = rules.initial_state(board_size)
        moves: list[int] = []
        positions: list[list[Any]] = [_position(state)]

        while not rules.is_terminal(state):
            legal = rules.legal_actions(state)
            action = int(legal[rng.integers(0, len(legal))])
            state = rules.apply(state, action)
            moves.append(action)
            positions.append(_position(state))

        black, white = scoring.disc_counts(state)
        games.append(
            {
                "moves": moves,
                "positions": positions,
                "final_score": [black, white],
                "winner": "black" if black > white else "white" if white > black else "draw",
            }
        )

    return {
        "fixture": "games",
        "version": FIXTURE_VERSION,
        "board_size": board_size,
        "seed": seed,
        "games": games,
    }


def endgame_positions(
    *,
    per_level: int,
    board_size: int,
    seed: int,
    max_empties: int,
    max_games: int = 400,
) -> list[State]:
    """Positions with few enough empty squares to solve, drawn from random games.

    Random play rather than agent play, for the same reason ``sample_positions``
    gives: a trained agent avoids exactly the awkward endings a port breaks on --
    a side with one legal move, a side that must pass, a board one disc from a
    wipeout. Spread across the whole band rather than bunched at the easy end,
    because the shallow positions are the ones a wrong search accidentally gets
    right.

    ``per_level`` positions are wanted at each empty-square count, but not every
    count is equally reachable: a game that ends with the board unfilled never
    passes through one empty square, so the shallowest bands fill slowly and the
    very shallowest may not fill at all. The game budget is therefore a hard stop
    and the quota a target. Returning fewer positions than asked for is correct
    here; looping until an unreachable quota is met is not, and was the first
    version of this function.
    """
    rng = np.random.default_rng(seed)
    quota = dict.fromkeys(range(2, max_empties + 1), 0)
    full = geometry(board_size).full

    found: list[State] = []
    seen: set[tuple[int, int, int]] = set()

    for _ in range(max_games):
        if all(taken >= per_level for taken in quota.values()):
            break
        state = rules.initial_state(board_size)
        while not rules.is_terminal(state):
            legal = rules.legal_actions(state)
            state = rules.apply(state, int(legal[rng.integers(0, len(legal))]))

            open_squares = popcount(full & ~(state.black | state.white))
            if quota.get(open_squares, per_level) >= per_level:
                continue
            key = (state.black, state.white, int(state.to_move))
            if key in seen:
                continue
            seen.add(key)
            quota[open_squares] += 1
            found.append(state)

    found.sort(key=lambda s: (s.black, s.white, int(s.to_move)))
    return found


def endgame_fixture(
    *,
    per_level: int,
    board_size: int,
    seed: int,
    max_empties: int = 10,
) -> dict[str, Any]:
    """Exact endgame values, for the TypeScript solver to reproduce.

    The browser plays the puzzle endings out, which means it runs its own exact
    search -- a third implementation of the same thing, after the Python solver
    and the reference engine. A subtly wrong port would not crash. It would
    answer a puzzle with a move that is not best, and the page would state the
    result with the certainty this whole feature is built on.

    So the port is held to the standard the rules were: the expectations are
    generated from the frozen Python solver rather than written by hand, and CI
    regenerates and compares them. Unlike ``puzzles``, this one **can** be
    regenerated anywhere -- there is no network and no torch in it, only random
    play and an exact search, both seeded.

    Positions where the mover must pass carry an empty ``margins`` list. They are
    included on purpose: the pass rule is where an endgame search goes wrong
    quietly, because a search that mishandles it still returns a legal move.
    """
    cases = []
    for state in endgame_positions(
        per_level=per_level, board_size=board_size, seed=seed, max_empties=max_empties
    ):
        placements = [
            action for action in rules.legal_actions(state) if action != pass_action(board_size)
        ]
        margins: list[list[int]] = []
        if placements:
            solved = solve_root(state, max_empties=max_empties)
            margins = [[int(move), margin] for move, margin in sorted(solved.margins.items())]
        cases.append(
            [
                *_position(state),
                empties(state),
                solve_exact(state, max_empties=max_empties),
                margins,
            ]
        )

    return {
        "fixture": "endgame",
        "version": FIXTURE_VERSION,
        "board_size": board_size,
        "seed": seed,
        "max_empties": max_empties,
        "pass_action": pass_action(board_size),
        "schema": ["black_hex", "white_hex", "to_move", "empties", "value", "margins"],
        "cases": cases,
    }


def puzzles_fixture(
    puzzles: Sequence[Puzzle],
    *,
    board_size: int,
    seed: int,
) -> dict[str, Any]:
    """The endgame curriculum, in the shape every other fixture here uses.

    Not part of ``write_fixtures`` and not in the CI drift loop, unlike the five
    fixtures above, and for a reason worth stating rather than discovering.
    Those are generated from the frozen rules in under a minute, so CI can
    regenerate them and diff, which is what makes "generated, never typed"
    enforced instead of merely intended. Puzzles are mined by playing real games
    with the trained network and solving the endings exactly -- minutes to hours,
    and dependent on torch floating-point arithmetic that is not promised to be
    identical on another machine. A diff against a re-run would fail for reasons
    that are not mistakes.

    What protects this file instead is stronger: every shipped puzzle is re-solved
    and its stored answers checked against the solver. A hand-edited row is
    dangerous because it would teach a wrong move, and that is exactly what
    re-solving catches, while a diff would only notice that somebody had been
    there.

    ``cases`` arrive already ordered -- by stage, then by difficulty inside the
    stage -- because the progression is the generator's responsibility. The app
    reads the file in order and never re-derives it.
    """
    stages = sorted({puzzle.stage for puzzle in puzzles})
    by_number = {stage.number: stage for stage in STAGES}

    cases = [
        [
            puzzle.stage,
            *_position(puzzle.state),
            puzzle.empties,
            [[int(move), margin] for move, margin in sorted(puzzle.margins.items())],
            puzzle.best,
            [int(move) for move in puzzle.principal_variation],
            puzzle.difficulty,
            int(puzzle.tempting_move),
            int(puzzle.greedy_falls),
        ]
        for puzzle in puzzles
    ]

    return {
        "fixture": "puzzles",
        "version": FIXTURE_VERSION,
        "board_size": board_size,
        "seed": seed,
        "pass_action": pass_action(board_size),
        "stages": [
            {
                "stage": number,
                "empties": [by_number[number].low, by_number[number].high],
                "title": by_number[number].title,
                "teaches": by_number[number].teaches,
            }
            for number in stages
        ],
        "schema": [
            "stage",
            "black_hex",
            "white_hex",
            "to_move",
            "empties",
            "margins",
            "best",
            "pv",
            "difficulty",
            "tempting",
            "greedy_falls",
        ],
        "cases": cases,
    }


# ---------------------------------------------------------------------------


def write_fixtures(
    destination: Path,
    *,
    board_size: int = 8,
    seed: int = 20260830,
    rules_count: int = 1000,
    encoding_count: int = 200,
    network_count: int = 64,
    search_count: int = 40,
    games_count: int = 20,
    endgame_per_level: int = 8,
    simulations: int = 64,
    onnx_path: Path | None = None,
) -> dict[str, int]:
    """Write every fixture into ``destination``, returning file sizes in bytes.

    The network fixture is skipped when no ONNX file is given, so the rules,
    encoding, search and game fixtures can be regenerated without a trained
    model present -- which is what CI does when it checks they are still current.

    The committed sizes are deliberately modest, following the split this repo
    already uses for the differential test: enough coverage to catch a regression
    within minutes of a push, with a far larger run (``rules_count=20000``)
    regenerated nightly. Every file stays under the 500 KB limit that keeps large
    artifacts out of git history.
    """
    destination.mkdir(parents=True, exist_ok=True)
    written: dict[str, int] = {}

    payloads: dict[str, dict[str, Any]] = {
        "rules": rules_fixture(count=rules_count, board_size=board_size, seed=seed),
        "encoding": encoding_fixture(count=encoding_count, board_size=board_size, seed=seed + 1),
        "search": search_fixture(
            count=search_count, board_size=board_size, seed=seed + 2, simulations=simulations
        ),
        "games": games_fixture(count=games_count, board_size=board_size, seed=seed + 3),
        "endgame": endgame_fixture(
            per_level=endgame_per_level, board_size=board_size, seed=seed + 5
        ),
    }
    if onnx_path is not None:
        payloads["network"] = network_fixture(
            count=network_count, board_size=board_size, seed=seed + 4, onnx_path=onnx_path
        )

    for name, payload in payloads.items():
        written[name] = write_fixture_file(destination / f"{name}.json", payload)

    return written


def write_fixture_file(path: Path, payload: dict[str, Any]) -> int:
    """Write one fixture and return its size in bytes.

    Separators without spaces: these files are committed, and a fixture is read
    by a test rather than by a person. In one function so that a fixture written
    outside ``write_fixtures`` -- the puzzles file, which cannot be regenerated
    cheaply enough to belong there -- cannot drift into a different format and
    quietly produce a whole-file diff the next time the others are regenerated.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    # LF regardless of platform. ``.gitattributes`` normalises the committed copy,
    # but CI regenerates these on Linux and byte-compares them against what is in
    # the repository, so a writer that followed the platform would make the check
    # depend on which machine last ran it.
    path.write_text(
        json.dumps(payload, separators=(",", ":"), sort_keys=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return path.stat().st_size


def player_of(code: int) -> Player:
    """Turn the fixture's ``to_move`` code back into a player."""
    return Player.BLACK if code == int(Player.BLACK) else Player.WHITE


def state_of(black_hex: str, white_hex: str, to_move: int, board_size: int) -> State:
    """Rebuild a state from a fixture row, so tests can round-trip one."""
    return State(
        black=int(black_hex, 16),
        white=int(white_hex, 16),
        to_move=player_of(to_move),
        size=board_size,
    )
