/**
 * The tree search, ported from `reversi.search`.
 *
 * The idea in one paragraph: from the current position, run many short
 * "simulations". Each one walks down the tree choosing moves that look good,
 * stops at a position the tree has not opened yet, asks the network how that
 * position looks, and carries the answer back up. Moves that keep leading
 * somewhere good get walked more often, so after a few hundred simulations the
 * number of visits each move received is a much better opinion than the
 * network's first guess.
 *
 * Two contracts govern this file, and both are the kind that fail silently.
 *
 * **C2, the value sign.** A value is always from the point of view of whoever is
 * about to move. Walking a result back up the tree crosses one turn boundary per
 * step, so the sign flips exactly once per step: good for me is bad for whoever
 * chose the move that got here. Get this wrong and the search still returns
 * legal moves -- it just prefers losing ones, and the only symptom is an agent
 * that seems not to learn.
 *
 * **C5, illegal moves.** A node's arrays cover its legal moves and nothing else.
 * A position with seven legal moves has arrays of length seven, not sixty-five.
 * There is no entry for an illegal move, so no amount of searching can reach
 * one. This is structural rather than defensive: there is nothing to mask, so a
 * masking bug cannot exist.
 *
 * Checked against visit counts generated by the Python search in
 * `tests/search.test.ts`.
 */

import { legalActions, apply, isTerminal, result, type Action, type State } from "./rules";

export interface SearchConfig {
  readonly nSimulations: number;
  /** How much to trust the network's preference over measured results. */
  readonly cPuct: number;
  /** How pessimistic to be about a move nobody has tried yet. */
  readonly fpuReduction: number;
  /**
   * Stop after this many milliseconds even if the simulation budget is unspent.
   *
   * A fixed simulation count is a fixed amount of *work*, not a fixed amount of
   * *waiting*, and the two differ by more than an order of magnitude across the
   * devices this runs on. Measured on a 20-core laptop, 800 simulations takes
   * 2.8 seconds; on a phone it would be far worse, and a move that takes ten
   * seconds reads as a crash rather than as thinking.
   *
   * Capping by time makes the top difficulty mean "think hard for about this
   * long", which is what a player actually cares about, and it degrades on slow
   * hardware by searching less rather than by hanging. How many simulations it
   * actually managed comes back in the result, so the interface can say so
   * rather than claiming a number it did not reach.
   */
  readonly maxMillis?: number;
}

export const DEFAULT_CONFIG: SearchConfig = {
  nSimulations: 200,
  cPuct: 1.5,
  fpuReduction: 0.25,
};

/**
 * Something that can score positions.
 *
 * Returns raw, unmasked logits -- one per action including PASS -- and a value
 * in [-1, 1] from the point of view of the player to move. The network knows
 * nothing about legality; that belongs to the search.
 */
export interface Evaluator {
  evaluate(states: readonly State[]): Promise<{
    logits: Float32Array[];
    values: number[];
  }>;
}

export interface SearchResult {
  readonly actions: Action[];
  readonly visits: number[];
  readonly qValues: number[];
  /** The network's own opinion of the root, before any searching. */
  readonly rootValue: number;
  readonly boardSize: number;
  /** Simulations actually run, which a time budget may cut short. */
  readonly simulations: number;
  /** True when the time budget stopped the search before its count was spent. */
  readonly cutShort: boolean;
}

/**
 * Turn raw logits into probabilities over the legal moves only.
 *
 * `Math.fround` on the way in because the Python evaluator hands the search
 * float32 values, and the softmax is then computed in double precision. Reading
 * them at full double precision here would make this port's priors differ from
 * the reference in the last few digits, for no reason.
 *
 * The maximum is subtracted before exponentiating. A logit of +90 overflows to
 * `Infinity` otherwise, and the whole distribution becomes `NaN` -- which then
 * spreads through the tree without ever raising anything.
 */
export function priorsFromLogits(logits: Float32Array | number[], actions: readonly Action[]): number[] {
  const picked = actions.map((a) => Math.fround(logits[a]!));

  let largest = -Infinity;
  for (const value of picked) if (value > largest) largest = value;

  if (!Number.isFinite(largest)) {
    // Every legal move was -Infinity, or the network produced nonsense.
    // Refusing to guess beats returning NaN and poisoning the tree.
    return picked.map(() => 1 / actions.length);
  }

  const exp = picked.map((value) => Math.exp(value - largest));
  let total = 0;
  for (const value of exp) total += value;

  if (!Number.isFinite(total) || total <= 0) {
    return picked.map(() => 1 / actions.length);
  }
  return exp.map((value) => value / total);
}

/** A position, plus what the search has learned about the moves out of it. */
class Node {
  state: State;
  actions: Action[] = [];
  prior: number[] = [];
  visits: number[] = [];
  valueSum: number[] = [];
  children: (Node | null)[] = [];
  expanded = false;

  /** The network's opinion of this position, from its own mover's view. */
  netValue = 0;

  /**
   * The exact result of a finished position. Terminal nodes are never sent to
   * the network -- the answer is known, and a guess could only be worse.
   */
  terminalValue: number | null = null;

  constructor(state: State) {
    this.state = state;
  }

  get nActions(): number {
    return this.actions.length;
  }

  get totalVisits(): number {
    let total = 0;
    for (const n of this.visits) total += n;
    return total;
  }

  q(index: number): number {
    const visits = this.visits[index]!;
    return visits ? this.valueSum[index]! / visits : 0;
  }

  /** How this node is going overall, from its own mover's point of view. */
  meanValue(): number {
    const total = this.totalVisits;
    if (total === 0) return this.netValue;
    let sum = 0;
    for (const value of this.valueSum) sum += value;
    return sum / total;
  }

  openWith(actions: Action[], priors: number[], netValue: number): void {
    if (actions.length === 0) {
      throw new Error("cannot expand a node with no legal actions -- it is terminal");
    }
    this.actions = actions;
    this.prior = priors;
    this.visits = new Array<number>(actions.length).fill(0);
    this.valueSum = new Array<number>(actions.length).fill(0);
    this.children = new Array<Node | null>(actions.length).fill(null);
    this.netValue = netValue;
    this.expanded = true;
  }
}

export class SearchError extends Error {}

export class MCTS {
  constructor(
    private readonly evaluator: Evaluator,
    private readonly config: SearchConfig = DEFAULT_CONFIG,
  ) {}

  /**
   * Search from `state` and report what was found.
   *
   * No exploration noise anywhere in this file. Noise belongs to self-play,
   * where it stops the agent playing the same game against itself forever; an
   * agent playing a person with it switched on is quietly playing worse than it
   * can (contract C7). Leaving it out entirely is stronger than remembering to
   * set it to zero.
   *
   * `signal` lets the interface abandon a search the player no longer wants --
   * they changed difficulty, took a move back, or started a new game. Without
   * it the worker would finish the whole budget before noticing.
   */
  async run(state: State, signal?: AbortSignal): Promise<SearchResult> {
    if (isTerminal(state)) {
      throw new SearchError("cannot search a finished position: there is no move to choose");
    }

    const root = new Node(state);
    await this.expand(root);

    const deadline =
      this.config.maxMillis === undefined ? Infinity : performance.now() + this.config.maxMillis;

    let ran = 0;
    for (let i = 0; i < this.config.nSimulations; i++) {
      if (signal?.aborted) break;
      // Checked before the simulation rather than after, so the budget is a
      // ceiling on how long a player waits rather than a ceiling plus one more
      // simulation. At the top level one simulation is several milliseconds.
      if (performance.now() >= deadline) break;
      const { leaf, path } = this.descend(root);
      backup(path, await this.leafValue(leaf));
      ran++;
    }

    return {
      actions: [...root.actions],
      visits: [...root.visits],
      qValues: root.actions.map((_, index) => root.q(index)),
      rootValue: root.netValue,
      boardSize: state.size,
      simulations: ran,
      cutShort: ran < this.config.nSimulations && !signal?.aborted,
    };
  }

  /** Walk from the root to a position the tree has not opened up yet. */
  private descend(root: Node): { leaf: Node; path: Array<[Node, number]> } {
    let node = root;
    const path: Array<[Node, number]> = [];

    while (node.expanded) {
      const index = this.select(node);
      path.push([node, index]);
      let child = node.children[index];
      if (child == null) {
        child = new Node(apply(node.state, node.actions[index]!));
        node.children[index] = child;
      }
      node = child;
    }

    return { leaf: node, path };
  }

  /** Pick the child to descend into: measured value plus an exploration bonus. */
  private select(node: Node): number {
    const { cPuct, fpuReduction } = this.config;

    const total = node.totalVisits;
    // The textbook formula uses sqrt(total), which is 0 before any child has
    // been visited -- so the exploration term vanishes for every move and the
    // first simulation ignores the network entirely, taking whichever move
    // happens to be numbered lowest. Flooring at 1 makes that first choice
    // follow the network's preference, which is the entire point of having one.
    // Identical from the second simulation onward.
    const sqrtTotal = total > 0 ? Math.sqrt(total) : 1;

    // A move nobody has tried has no measured value, so it borrows the parent's
    // -- discounted, and discounted further once a good share of the parent's
    // prior has already been explored. Using 0 here instead is a common silent
    // bug: it makes early search behave breadth-first regardless of what the
    // network said.
    let exploredPrior = 0;
    for (let i = 0; i < node.nActions; i++) {
      if (node.visits[i]! > 0) exploredPrior += node.prior[i]!;
    }
    const unvisitedValue = node.meanValue() - fpuReduction * Math.sqrt(exploredPrior);

    let bestIndex = 0;
    let bestScore = -Infinity;
    for (let index = 0; index < node.nActions; index++) {
      const visits = node.visits[index]!;
      const q = visits ? node.valueSum[index]! / visits : unvisitedValue;
      const u = (cPuct * node.prior[index]! * sqrtTotal) / (1 + visits);
      const score = q + u;
      if (score > bestScore) {
        bestScore = score;
        bestIndex = index;
      }
    }
    return bestIndex;
  }

  /** The value of a freshly reached position, from *its* mover's point of view. */
  private async leafValue(node: Node): Promise<number> {
    const exact = terminalValue(node);
    if (exact !== null) return exact;

    await this.expand(node);
    return node.netValue;
  }

  private async expand(node: Node): Promise<void> {
    const { logits, values } = await this.evaluator.evaluate([node.state]);
    const actions = legalActions(node.state);
    node.openWith(actions, priorsFromLogits(logits[0]!, actions), Math.fround(values[0]!));
  }
}

function terminalValue(node: Node): number | null {
  if (!isTerminal(node.state)) return null;
  if (node.terminalValue === null) node.terminalValue = result(node.state);
  return node.terminalValue;
}

/**
 * Record a result along the path that produced it -- contract C2.
 *
 * `leafValue` is from the leaf's mover's point of view. Each step up crosses one
 * turn boundary, so the sign flips exactly once per step. Passing needs no
 * special case: a pass changes whose turn it is just like a placement does, so
 * the alternation holds straight through it.
 */
function backup(path: Array<[Node, number]>, leafValue: number): void {
  let value = leafValue;
  for (let i = path.length - 1; i >= 0; i--) {
    const [node, index] = path[i]!;
    value = -value;
    node.visits[index] = node.visits[index]! + 1;
    node.valueSum[index] = node.valueSum[index]! + value;
  }
}

// ---------------------------------------------------------------------------

/** The most-visited move. Ties go to the lower index, so this is deterministic. */
export function bestAction(result: SearchResult): Action {
  let best = 0;
  for (let i = 1; i < result.actions.length; i++) {
    if (result.visits[i]! > result.visits[best]!) best = i;
  }
  return result.actions[best]!;
}

/** The search's estimate for the player to move at the root, in [-1, 1]. */
export function searchValue(result: SearchResult): number {
  let total = 0;
  for (const n of result.visits) total += n;
  if (total === 0) return result.rootValue;

  let weighted = 0;
  for (let i = 0; i < result.visits.length; i++) {
    weighted += result.qValues[i]! * result.visits[i]!;
  }
  return weighted / total;
}

/** Full-width visit counts, for the heat map. Zero on every illegal action. */
export function visitCounts(result: SearchResult): number[] {
  const counts = new Array<number>(result.boardSize * result.boardSize + 1).fill(0);
  result.actions.forEach((action, index) => {
    counts[action] = result.visits[index]!;
  });
  return counts;
}
