/**
 * The endgame curriculum, decoded from the file the miner produced.
 *
 * `puzzles.json` is generated by `reversi puzzles`: positions the side to move
 * wins, where a tempting move throws it away, with the exact final disc
 * difference after *every* legal move. Nothing here computes any of that. There
 * is no solver in the browser, and that is the point -- an alpha-beta search deep
 * enough to settle thirteen empty squares is seconds of work in Python and an
 * open question in TypeScript, so the answers are precomputed and this file only
 * has to read them.
 *
 * **Rows are read through the file's own `schema`, not by position.** The five
 * engine fixtures are compared against a regeneration in CI, so a column added
 * in the wrong place fails there. This file is not regenerated in CI -- mining
 * takes an hour and a trained network -- so a shifted column would arrive
 * silently and the page would draw a board out of a difficulty score. Looking
 * each field up by name costs one pass over sixty rows and removes that.
 *
 * Boards are hex strings, never JSON numbers: a 64-bit board is not exact as a
 * JavaScript number, and a position that loses its top bits is a position that
 * never existed.
 */

import { fromHex } from "../engine/bitboard";
import { BLACK, WHITE, type Action, type Player, type State } from "../engine/rules";
import fixture from "../engine/__fixtures__/puzzles.json";

export interface Stage {
  readonly number: number;
  readonly title: string;
  /** One sentence on what this stage is for, shown beside the board. */
  readonly teaches: string;
  /** Inclusive band of empty-square counts, as mined. */
  readonly empties: readonly [number, number];
}

export interface Puzzle {
  /**
   * Stable across regenerations, because it is the position itself. A puzzle
   * that survives a re-mine keeps whatever progress a visitor had against it,
   * and one that does not survive simply stops being listed.
   */
  readonly id: string;
  readonly stage: number;
  readonly state: State;
  readonly empties: number;
  /** Exact final disc difference after each legal move, for the side to move. */
  readonly margins: ReadonlyMap<Action, number>;
  readonly best: number;
  readonly bestMoves: readonly Action[];
  /** Moves that still win. Never empty: an unwinnable position is not mined. */
  readonly winningMoves: readonly Action[];
  /** One line of perfect play from here, ending the game. Includes passes. */
  readonly principalVariation: readonly Action[];
  readonly difficulty: number;
  /** The move the network's policy liked most, which may be a losing one. */
  readonly tempting: Action;
  /** True when every move that flips the most discs loses. */
  readonly greedyFalls: boolean;
}

export const BOARD_SIZE: number = fixture.board_size;

function fail(why: string): never {
  // Loudly, at module load, rather than as an undefined halfway through a
  // render. A curriculum that cannot be read is not something to paper over:
  // every screen built from it would be wrong in a way nobody could see.
  throw new Error(`puzzles.json is not usable: ${why}`);
}

function decode(): { stages: Stage[]; puzzles: Puzzle[] } {
  const raw = fixture as unknown as {
    fixture: string;
    board_size: number;
    stages: Array<{ stage: number; title: string; teaches: string; empties: number[] }>;
    schema: string[];
    cases: unknown[][];
  };

  if (raw.fixture !== "puzzles") fail(`it says it is a "${raw.fixture}" fixture`);

  const at = (field: string): number => {
    const index = raw.schema.indexOf(field);
    if (index < 0) fail(`no "${field}" column`);
    return index;
  };
  const columns = {
    stage: at("stage"),
    black: at("black_hex"),
    white: at("white_hex"),
    toMove: at("to_move"),
    empties: at("empties"),
    margins: at("margins"),
    best: at("best"),
    pv: at("pv"),
    difficulty: at("difficulty"),
    tempting: at("tempting"),
    greedyFalls: at("greedy_falls"),
  };

  const stages: Stage[] = raw.stages.map((entry) => {
    const [low, high] = entry.empties;
    if (low === undefined || high === undefined) fail(`stage ${entry.stage} has no empties band`);
    return {
      number: entry.stage,
      title: entry.title,
      teaches: entry.teaches,
      empties: [low, high] as const,
    };
  });

  const puzzles: Puzzle[] = raw.cases.map((row, position) => {
    const blackHex = row[columns.black] as string;
    const whiteHex = row[columns.white] as string;
    const toMove = row[columns.toMove] as number;
    const pairs = row[columns.margins] as Array<[number, number]>;
    const margins = new Map<Action, number>(pairs);
    const best = row[columns.best] as number;

    if (margins.size < 2) fail(`puzzle ${position} offers fewer than two moves`);
    if (best <= 0) fail(`puzzle ${position} cannot be won, so it is not a puzzle`);

    return {
      id: `${blackHex}:${whiteHex}:${toMove}`,
      stage: row[columns.stage] as number,
      state: {
        black: fromHex(blackHex),
        white: fromHex(whiteHex),
        toMove: (toMove === BLACK ? BLACK : WHITE) as Player,
        size: raw.board_size,
      },
      empties: row[columns.empties] as number,
      margins,
      best,
      bestMoves: [...margins].filter(([, margin]) => margin === best).map(([move]) => move),
      winningMoves: [...margins].filter(([, margin]) => margin > 0).map(([move]) => move),
      principalVariation: row[columns.pv] as number[],
      difficulty: row[columns.difficulty] as number,
      tempting: row[columns.tempting] as number,
      greedyFalls: (row[columns.greedyFalls] as number) === 1,
    };
  });

  return { stages, puzzles };
}

const decoded = decode();

export const STAGES: readonly Stage[] = decoded.stages;

/**
 * Every puzzle, in the order the generator arranged them: by stage, then by
 * derived difficulty inside the stage, easiest first.
 *
 * Read, never re-sorted. The progression is the generator's responsibility --
 * it is the side that can see the solve -- and a second ordering here would be
 * a second opinion about which puzzle is harder.
 */
export const PUZZLES: readonly Puzzle[] = decoded.puzzles;

export function stageNumbers(): readonly number[] {
  return STAGES.map((stage) => stage.number);
}

export function stageOf(number: number): Stage {
  const found = STAGES.find((stage) => stage.number === number);
  if (found === undefined) fail(`no stage ${number}`);
  return found;
}

export function puzzlesInStage(stage: number): readonly Puzzle[] {
  return PUZZLES.filter((puzzle) => puzzle.stage === stage);
}
