/**
 * The browser's exact search against the Python solver's answers.
 *
 * This is the same discipline `rules.test.ts` applies to the rules, for the same
 * reason. The puzzle page plays an ending out against this search and then
 * states the result as certain — so a subtly wrong port would not crash, it
 * would answer with a move that is not best and the page would say the resulting
 * score was proved.
 *
 * Nothing here is a hand-written belief about what an ending is worth. Every
 * expectation was generated by `reversi export-fixtures` from the solver that
 * Edax agreed with on 210 positions, and CI regenerates and byte-compares the
 * file, so the two cannot drift apart quietly.
 *
 * Two sources, deliberately. `endgame.json` is broad and awkward — random play,
 * two to ten empty squares, including a position where the mover must pass.
 * `puzzles.json` is deep and realistic: the sixty positions actually shipped, at
 * up to thirteen empty squares, which is further than the generated fixture goes
 * and is exactly where a search runs out of patience.
 */

import { describe, expect, it } from "vitest";

import endgameFixture from "../src/games/reversi/engine/__fixtures__/endgame.json";
import puzzlesFixture from "../src/games/reversi/engine/__fixtures__/puzzles.json";
import { fromHex } from "../src/games/reversi/engine/bitboard";
import {
  MAX_EMPTIES,
  TooManyEmptiesError,
  bestMove,
  emptyCount,
  solveExact,
  solveRoot,
} from "../src/games/reversi/engine/endgame";
import {
  BLACK,
  WHITE,
  apply,
  initialState,
  isTerminal,
  legalActions,
  passAction,
  type Player,
  type State,
} from "../src/games/reversi/engine/rules";

function stateOf(
  blackHex: string,
  whiteHex: string,
  toMove: number,
  size: number,
): State {
  return {
    black: fromHex(blackHex),
    white: fromHex(whiteHex),
    toMove: (toMove === BLACK ? BLACK : WHITE) as Player,
    size,
  };
}

interface Row {
  state: State;
  empties: number;
  value: number;
  margins: Array<[number, number]>;
}

const endgameRows: Row[] = endgameFixture.cases.map((row) => {
  const [blackHex, whiteHex, toMove, empties, value, margins] = row as [
    string,
    string,
    number,
    number,
    number,
    Array<[number, number]>,
  ];
  return {
    state: stateOf(blackHex, whiteHex, toMove, endgameFixture.board_size),
    empties,
    value,
    margins,
  };
});

const puzzleRows: Row[] = puzzlesFixture.cases.map((row) => {
  const schema = puzzlesFixture.schema;
  const at = (name: string) => row[schema.indexOf(name)];
  return {
    state: stateOf(
      at("black_hex") as string,
      at("white_hex") as string,
      at("to_move") as number,
      puzzlesFixture.board_size,
    ),
    empties: at("empties") as number,
    value: at("best") as number,
    margins: at("margins") as Array<[number, number]>,
  };
});

describe("the exact value of a position", () => {
  it("matches the Python solver on every generated position", () => {
    expect(endgameRows.length).toBeGreaterThanOrEqual(50);
    for (const row of endgameRows) {
      expect(emptyCount(row.state)).toBe(row.empties);
      expect(solveExact(row.state)).toBe(row.value);
    }
  });

  it("matches on the shipped puzzles, which go deeper than the fixture", () => {
    const deepest = Math.max(...puzzleRows.map((r) => r.empties));
    expect(deepest).toBeGreaterThan(
      Math.max(...endgameRows.map((r) => r.empties)),
    );
    for (const row of puzzleRows) {
      // A puzzle's `best` is the value of the position, since the mover picks.
      expect(solveExact(row.state)).toBe(row.value);
    }
  });

  it("gets a forced pass right", () => {
    // The pass rule is where an endgame search goes wrong quietly: a search that
    // mishandles it still returns a legal move, and only the score is wrong.
    const passing = endgameRows.filter((row) => row.margins.length === 0);
    expect(passing.length).toBeGreaterThan(0);
    for (const row of passing) {
      expect(legalActions(row.state)).toEqual([passAction(row.state.size)]);
      expect(solveExact(row.state)).toBe(row.value);
    }
  });
});

describe("the value of every move", () => {
  it("matches the Python solver, move for move, on the generated positions", () => {
    for (const row of endgameRows) {
      if (row.margins.length === 0) continue;
      const got = solveRoot(row.state);
      expect([...got].sort((a, b) => a[0] - b[0])).toEqual(row.margins);
    }
  });

  // Explicitly slow, and worth it. Ranking every move of a thirteen-empty
  // position is the most expensive thing this search is ever asked to do -- far
  // more than the page needs, which is one reply -- and doing it sixty times is
  // several seconds. The alternative is checking the deep stages less
  // thoroughly, which is where a port is most likely to be wrong.
  it("matches on every move of every shipped puzzle", () => {
    for (const row of puzzleRows) {
      const got = solveRoot(row.state);
      expect([...got].sort((a, b) => a[0] - b[0])).toEqual(row.margins);
    }
  }, 60_000);

  it("agrees with the single-value search about the best on offer", () => {
    // Two different code paths through the same search: one full window per root
    // move, versus one search with pruning between them. They must not disagree.
    for (const row of endgameRows) {
      if (row.margins.length === 0) continue;
      expect(Math.max(...solveRoot(row.state).values())).toBe(
        solveExact(row.state),
      );
    }
  });
});

describe("choosing a reply", () => {
  it("plays a move that cannot be improved on", () => {
    for (const row of puzzleRows) {
      const margins = new Map(row.margins);
      const best = Math.max(...margins.values());
      expect(margins.get(bestMove(row.state))).toBe(best);
    }
  });

  it("answers the same position the same way every time", () => {
    // A retry has to pose the same puzzle. An opponent that varied its reply
    // would make a position unrepeatable, which is worse than a predictable one.
    for (const row of puzzleRows.slice(0, 12)) {
      expect(bestMove(row.state)).toBe(bestMove(row.state));
    }
  });

  it("passes when there is nothing to place", () => {
    const passing = endgameRows.find((row) => row.margins.length === 0)!;
    expect(bestMove(passing.state)).toBe(passAction(passing.state.size));
  });

  it("plays an ending out to a finish, and the score is the one promised", () => {
    // The whole point of the search existing in the browser. If perfect play
    // from both sides did not land on the value the solver reported, the page
    // would be promising a score it cannot produce.
    for (const row of puzzleRows.slice(0, 20)) {
      let state = row.state;
      let guard = 0;
      while (!isTerminal(state) && guard++ < 70) {
        state = apply(state, bestMove(state));
      }
      expect(isTerminal(state)).toBe(true);

      const { black, white } = countDiscs(state);
      const forMover =
        row.state.toMove === BLACK ? black - white : white - black;
      expect(forMover).toBe(row.value);
    }
  }, 30_000);
});

describe("the guard rail", () => {
  it("refuses a position it cannot finish in time", () => {
    // The opening has 60 empty squares. Refusing is the difference between an
    // error a caller can see and a tab that never responds again.
    expect(() => solveExact(initialState(8))).toThrow(TooManyEmptiesError);
    expect(emptyCount(initialState(8))).toBeGreaterThan(MAX_EMPTIES);
  });

  it("accepts a position exactly at the limit", () => {
    const deepest = puzzleRows.reduce((a, b) =>
      a.empties >= b.empties ? a : b,
    );
    expect(deepest.empties).toBeLessThanOrEqual(MAX_EMPTIES);
    expect(() => solveExact(deepest.state)).not.toThrow();
  });
});

function countDiscs(state: State): { black: number; white: number } {
  const bits = (lo: number, hi: number) => {
    let count = 0;
    for (let i = 0; i < 32; i++) count += (lo >>> i) & 1;
    for (let i = 0; i < 32; i++) count += (hi >>> i) & 1;
    return count;
  };
  return {
    black: bits(state.black.lo, state.black.hi),
    white: bits(state.white.lo, state.white.hi),
  };
}
