/**
 * The TypeScript engine against the frozen Python one.
 *
 * Every expectation here was generated by `reversi export-fixtures`, from the
 * same engine the agent was trained against. Nothing in this file is a
 * hand-written belief about what the rules are -- that is the point. A test I
 * wrote from memory would encode what I think Reversi does; these encode what
 * the agent actually learned.
 *
 * This is the browser's half of the differential test that has guarded the
 * Python engine since day three.
 */

import { describe, expect, it } from "vitest";

import rulesFixture from "../src/engine/__fixtures__/rules.json";
import gamesFixture from "../src/engine/__fixtures__/games.json";
import encodingFixture from "../src/engine/__fixtures__/encoding.json";

import { fromHex, toHex, indices, popcount, type Bits } from "../src/engine/bitboard";
import {
  BLACK,
  WHITE,
  apply,
  discCounts,
  flips,
  initialState,
  isTerminal,
  legalActions,
  legalPlacements,
  passAction,
  type Player,
  type State,
} from "../src/engine/rules";
import { encode, planeBits } from "../src/engine/features";

const SIZE = rulesFixture.board_size;

function stateOf(blackHex: string, whiteHex: string, toMove: number, size = SIZE): State {
  return {
    black: fromHex(blackHex),
    white: fromHex(whiteHex),
    toMove: (toMove === 0 ? BLACK : WHITE) as Player,
    size,
  };
}

function hex(b: Bits): string {
  return toHex(b).replace(/^0+(?=.)/, "");
}

// ===========================================================================
// The rules fixture
// ===========================================================================

describe("legal moves and flips match the Python engine", () => {
  const cases = rulesFixture.cases as Array<
    [string, string, number, number[], Array<[number, string]>, number, number, number]
  >;

  it("has enough cases to mean something", () => {
    expect(cases.length).toBeGreaterThanOrEqual(1000);
  });

  it("agrees on the legal action list for every position", () => {
    const disagreements: string[] = [];
    for (const [black, white, toMove, legal] of cases) {
      const state = stateOf(black, white, toMove);
      const ours = legalActions(state);
      if (ours.join(",") !== legal.join(",")) {
        disagreements.push(`${black}/${white} to_move=${toMove}: ${ours} != ${legal}`);
      }
    }
    expect(disagreements).toEqual([]);
  });

  it("agrees on the exact set of discs every move flips", () => {
    // The sharpest check in the file. Legal-move generation and flipping share
    // the same eight-direction walk, so a direction whose edge guard is wrong
    // often still produces a believable legal set while flipping wrong discs.
    const disagreements: string[] = [];
    for (const [black, white, toMove, , flipList] of cases) {
      const state = stateOf(black, white, toMove);
      for (const [action, expected] of flipList) {
        const ours = hex(flips(state, action));
        if (ours !== expected) {
          disagreements.push(`${black}/${white} action=${action}: ${ours} != ${expected}`);
        }
      }
    }
    expect(disagreements).toEqual([]);
  });

  it("agrees on which positions are over", () => {
    for (const [black, white, toMove, , , terminal] of cases) {
      const state = stateOf(black, white, toMove);
      expect(isTerminal(state) ? 1 : 0).toBe(terminal);
    }
  });

  it("agrees on the score", () => {
    for (const [black, white, toMove, , , , blackDiscs, whiteDiscs] of cases) {
      const state = stateOf(black, white, toMove);
      expect(discCounts(state)).toEqual({ black: blackDiscs, white: whiteDiscs });
    }
  });

  it("covers the positions a port actually breaks on", () => {
    // A fixture of comfortable mid-game positions would pass an engine that
    // gets passing or termination wrong, which are two of the three things
    // this file is for.
    const pass = passAction(SIZE);
    const terminal = cases.filter((c) => c[5] === 1).length;
    const forcedPass = cases.filter((c) => c[3].length === 1 && c[3][0] === pass).length;
    const nearFull = cases.filter((c) => c[6] + c[7] >= SIZE * SIZE - 4).length;

    expect(terminal).toBeGreaterThan(0);
    expect(forcedPass).toBeGreaterThan(0);
    expect(nearFull).toBeGreaterThan(0);
  });
});

// ===========================================================================
// Whole games
// ===========================================================================

describe("a whole game stays in step", () => {
  // Each rule is checked in isolation above. Two engines can agree on every
  // rule and still drift apart once the moves are applied in sequence, which is
  // the failure this catches.
  const games = gamesFixture.games as Array<{
    moves: number[];
    positions: Array<[string, string, number]>;
    final_score: [number, number];
    winner: string;
  }>;

  it("replays every recorded game move for move", () => {
    for (const game of games) {
      let state = initialState(SIZE);

      game.moves.forEach((action, index) => {
        expect(legalActions(state)).toContain(action);
        state = apply(state, action);

        const [black, white, toMove] = game.positions[index + 1]!;
        expect(hex(state.black)).toBe(hex(fromHex(black)));
        expect(hex(state.white)).toBe(hex(fromHex(white)));
        expect(state.toMove).toBe(toMove);
      });

      expect(isTerminal(state)).toBe(true);
      const { black, white } = discCounts(state);
      expect([black, white]).toEqual(game.final_score);
    }
  });

  it("plays enough moves to be a real check", () => {
    const moves = games.reduce((total, game) => total + game.moves.length, 0);
    expect(moves).toBeGreaterThan(500);
  });
});

// ===========================================================================
// The board as the network sees it
// ===========================================================================

describe("the input encoding puts each disc on the right square", () => {
  const cases = encodingFixture.cases as Array<[string, string, number, [string, string, string]]>;

  it("matches the Python encoder plane for plane", () => {
    // Contract C1. Compared as bitmasks rather than as totals, because a
    // transposed board has exactly the right number of discs in it.
    for (const [black, white, toMove, planes] of cases) {
      const state = stateOf(black, white, toMove);
      const encoded = encode(state);
      const ours = [0, 1, 2].map((plane) => hex(planeBits(encoded, plane, SIZE)));
      expect(ours).toEqual(planes.map((p) => hex(fromHex(p))));
    }
  });

  it("gives the network the same board whichever colour is to move", () => {
    // The reason there is no colour plane: black to move and white to move with
    // the colours swapped are the same problem, so they get the same input and
    // share every bit of training signal.
    const [black, white, toMove] = cases[0]!;
    const state = stateOf(black, white, toMove);
    const mirrored: State = {
      black: state.white,
      white: state.black,
      toMove: state.toMove === BLACK ? WHITE : BLACK,
      size: SIZE,
    };
    expect(Array.from(encode(state))).toEqual(Array.from(encode(mirrored)));
  });
});

// ===========================================================================
// Bitboard arithmetic across the 32-bit seam
// ===========================================================================

describe("the 32-bit seam", () => {
  it("keeps the top squares of the board", () => {
    // The failure this guards against: a board turned into an ordinary
    // JavaScript number loses precision above 2^53, so squares 53-63 come back
    // wrong. Every one of the top eleven squares is checked individually.
    for (let square = 53; square < 64; square++) {
      const hexed = (BigInt(1) << BigInt(square)).toString(16).padStart(16, "0");
      const bits = fromHex(hexed);
      expect(indices(bits)).toEqual([square]);
      expect(popcount(bits)).toBe(1);
      expect(toHex(bits)).toBe(hexed);
    }
  });

  it("round-trips a full board through hex", () => {
    const full = fromHex("ffffffffffffffff");
    expect(popcount(full)).toBe(64);
    expect(indices(full).length).toBe(64);
    expect(toHex(full)).toBe("ffffffffffffffff");
  });

  it("does not let a disc wrap around the edge of the board", () => {
    // A shift that walks off column H and reappears on column A is the classic
    // bitboard bug. On the opening position it would invent legal moves in the
    // first column, so the count is the tell.
    const state = initialState(SIZE);
    expect(indices(legalPlacements(state)).sort((a, b) => a - b)).toEqual([19, 26, 37, 44]);
  });
});
