"""The puzzle curriculum: how it is derived, and whether the shipped file is true.

Two different jobs here, and the second one is the important one.

The first is ordinary: the selection rule and the difficulty score are code, and
code needs tests. Those run against positions built by hand, so a failure points
at one function.

The second is what protects a player. ``puzzles.json`` is generated by mining --
minutes of self-play and exact solving, dependent on torch arithmetic that is not
promised to be identical on another machine -- so it cannot be checked by
regenerating it and diffing, the way the five port fixtures are. What can be
checked anywhere is whether the answers in it are *true*: every puzzle is solved
again from its board and the stored table is compared move by move.

That is the stronger check regardless. A hand-edited puzzle file is dangerous
because it would tell somebody their winning move loses, with an interface that
says the answer is certain. Re-solving catches exactly that; a diff would only
notice that the file had been touched.
"""

from __future__ import annotations

import json
from itertools import pairwise
from pathlib import Path

import numpy as np
import pytest

from reversi.agents.edax import board_string, obf_string, square_index, square_name
from reversi.endgame.puzzles import (
    STAGES,
    MiningError,
    Puzzle,
    difficulty_of,
    stage_for,
    write_obf,
)
from reversi.endgame.solver import RootSolution, empties, solve_root
from reversi.game import rules, scoring
from reversi.game.state import State
from reversi.types import Player, pass_action
from reversi.web.fixtures import state_of

FIXTURE = Path("web/src/games/reversi/engine/__fixtures__/puzzles.json")

# Puzzles at or below this many empty squares are re-solved in the fast test
# lane. Above it the solve is seconds rather than milliseconds, so the whole file
# is re-verified in the slow lane instead. Both lanes use the same code; the only
# difference is how much of the file they cover.
FAST_LANE_EMPTIES = 9


def load_fixture() -> dict:
    if not FIXTURE.exists():  # pragma: no cover - only on a fresh clone
        pytest.skip(f"{FIXTURE} has not been generated yet")
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def rows(payload: dict) -> list[dict]:
    """Fixture rows as dicts, keyed by the schema the file carries."""
    schema = payload["schema"]
    return [dict(zip(schema, case, strict=True)) for case in payload["cases"]]


def state_of_row(row: dict, board_size: int) -> State:
    return state_of(row["black_hex"], row["white_hex"], row["to_move"], board_size)


# ---------------------------------------------------------------------------
# The curriculum's shape
# ---------------------------------------------------------------------------


class TestStages:
    def test_the_bands_are_ordered_and_do_not_overlap(self) -> None:
        """Stages have to partition the empty counts, or a position has two homes.

        Overlapping bands would let two puzzles of the same size land in
        different stages, which quietly destroys the one thing the progression
        promises: that later stages are bigger positions.
        """
        assert [stage.number for stage in STAGES] == list(range(1, len(STAGES) + 1))
        for earlier, later in pairwise(STAGES):
            assert earlier.low <= earlier.high
            assert earlier.high < later.low

    def test_every_count_in_range_belongs_to_exactly_one_stage(self) -> None:
        lowest, highest = STAGES[0].low, STAGES[-1].high
        for open_squares in range(lowest, highest + 1):
            matches = [stage for stage in STAGES if stage.contains(open_squares)]
            assert len(matches) == 1
            assert stage_for(open_squares) is matches[0]

    def test_a_position_outside_every_band_has_no_stage(self) -> None:
        assert stage_for(STAGES[0].low - 1) is None
        assert stage_for(STAGES[-1].high + 1) is None


# ---------------------------------------------------------------------------
# The difficulty score
# ---------------------------------------------------------------------------


class TestDifficulty:
    def test_a_narrow_win_scores_above_a_wide_one(self) -> None:
        """The dominant term, and the only one measured from the position alone.

        Same board size, same temptation: the position where one move in five
        holds the win is the harder ask.
        """
        flat = dict.fromkeys(range(5), 0.2)
        narrow = difficulty_of({0: 4, 1: -2, 2: -2, 3: -2, 4: -2}, flat, greedy=False)
        wide = difficulty_of({0: 4, 1: 4, 2: 4, 3: 4, 4: -2}, flat, greedy=False)
        assert narrow > wide

    def test_a_tempting_loss_scores_above_an_ignored_one(self) -> None:
        """A losing move nobody wants to play is not a trap."""
        margins = {0: 4, 1: -2, 2: -2, 3: -2, 4: -2}
        tempted = difficulty_of(margins, {0: 0.05, 1: 0.7, 2: 0.1, 3: 0.1, 4: 0.05}, greedy=False)
        alert = difficulty_of(margins, {0: 0.8, 1: 0.05, 2: 0.05, 3: 0.05, 4: 0.05}, greedy=False)
        assert tempted > alert

    def test_disc_grabbing_losing_adds_to_the_score(self) -> None:
        margins = {0: 4, 1: -2, 2: -2}
        policy = {0: 0.5, 1: 0.3, 2: 0.2}
        assert difficulty_of(margins, policy, greedy=True) > difficulty_of(
            margins, policy, greedy=False
        )

    def test_the_score_stays_on_its_scale(self) -> None:
        """An integer in 0-100, so a shipped order never hinges on a float compare.

        The top of the scale is reachable: one winning move, every drop of the
        network's probability resting on a loser, and disc-grabbing losing too.
        The bottom is not, and should not be -- scoring 0 would need a position
        with no losing move at all, which is by definition not a puzzle.
        """
        hardest = difficulty_of({0: 2, 1: -2}, {0: 0.0, 1: 1.0}, greedy=True)
        mildest = difficulty_of({0: 2, 1: 2, 2: -2}, {0: 0.5, 1: 0.5, 2: 0.0}, greedy=False)
        assert hardest == 100
        assert isinstance(hardest, int)
        assert 0 < mildest < hardest

    def test_it_refuses_a_position_that_is_not_a_puzzle(self) -> None:
        """No win, or no choice, means there is nothing to be difficult about."""
        with pytest.raises(MiningError, match="winnable"):
            difficulty_of({0: -2, 1: -4}, {0: 0.5, 1: 0.5}, greedy=False)
        with pytest.raises(MiningError, match="choice"):
            difficulty_of({0: 4}, {0: 1.0}, greedy=False)


# ---------------------------------------------------------------------------
# The Edax problem file
# ---------------------------------------------------------------------------


class TestObf:
    def test_the_two_notations_differ_only_in_the_letters(self) -> None:
        """``.obf`` writes X and O; Edax's own printout writes * and O.

        Worth pinning because the failure is silent: Edax reads a ``.obf`` line
        whose black discs are ``*`` as an empty board, solves that instead, and
        reports a disagreement that looks like a solver bug.
        """
        state = rules.initial_state(8)
        assert obf_string(state) == board_string(state).replace("*", "X")
        assert set(obf_string(state).split()[0]) <= {"X", "O", "-"}

    def test_a_written_line_parses_back_to_the_same_position(self, tmp_path: Path) -> None:
        state = _five_empty_position()
        solution = solve_root(state, empties_to_winner=True)
        puzzle = _puzzle_stub(state, solution)

        destination = tmp_path / "endgame.obf"
        written = write_obf(destination, [puzzle])
        line = destination.read_text(encoding="utf-8").strip()

        assert written == len(destination.read_bytes())
        board, _, scores = line.partition(";")
        squares, side = board.split()
        assert len(squares) == 64
        assert side == ("X" if state.to_move is Player.BLACK else "O")

        parsed = {}
        for item in scores.split(";"):
            if item.strip():
                name, _, margin = item.strip().partition(":")
                parsed[square_index(name)] = int(margin)
        assert parsed == solution.margins

    def test_scores_are_written_best_first(self, tmp_path: Path) -> None:
        """Edax's own problem files are ordered that way, and a reader expects it."""
        state = _five_empty_position()
        solution = solve_root(state, empties_to_winner=True)
        destination = tmp_path / "endgame.obf"
        write_obf(destination, [_puzzle_stub(state, solution)])

        _, _, scores = destination.read_text(encoding="utf-8").strip().partition(";")
        values = [int(item.split(":")[1]) for item in scores.split(";") if item.strip()]
        assert values == sorted(values, reverse=True)

    def test_the_file_carries_edax_scoring_not_this_project_s(self) -> None:
        """The whole point of the file is that Edax will check it.

        These are the only numbers in the repository written in the other
        convention, so a mix-up would make a correct solver look broken against
        the reference engine -- the exact confusion the solver's own tests were
        built to rule out.
        """
        state = _five_empty_position()
        ours = solve_root(state)
        theirs = solve_root(state, empties_to_winner=True)
        stub = _puzzle_stub(state, theirs)
        assert stub.edax_margins == theirs.margins
        # And the two conventions really are different here, or this proves nothing.
        assert ours.margins != theirs.margins


# ---------------------------------------------------------------------------
# The shipped file
# ---------------------------------------------------------------------------


class TestShippedCurriculum:
    def test_the_file_matches_its_own_schema(self) -> None:
        payload = load_fixture()
        assert payload["fixture"] == "puzzles"
        assert payload["cases"], "the curriculum is empty"
        width = len(payload["schema"])
        for case in payload["cases"]:
            assert len(case) == width

    def test_boards_are_hex_strings_and_not_numbers(self) -> None:
        """A 64-bit board is not exact as a JSON number. Ports fail quietly on it."""
        payload = load_fixture()
        for row in rows(payload):
            assert isinstance(row["black_hex"], str)
            assert isinstance(row["white_hex"], str)
            int(row["black_hex"], 16)
            int(row["white_hex"], 16)

    def test_every_puzzle_is_winnable_and_offers_a_choice(self) -> None:
        payload = load_fixture()
        skip = pass_action(payload["board_size"])
        for row in rows(payload):
            state = state_of_row(row, payload["board_size"])
            placements = [a for a in rules.legal_actions(state) if a != skip]
            assert row["best"] > 0, "a position nobody can win is not a puzzle"
            assert len(placements) >= 2, "a forced move is not a puzzle"
            assert len(row["margins"]) == len(placements)

    def test_every_puzzle_has_a_way_to_go_wrong(self) -> None:
        """The selection rule, read back off the shipped file.

        A position where every move wins has no wrong answer, and one where the
        losing moves are unattractive teaches nothing. Either the network's first
        choice loses, or grabbing the most discs does.
        """
        payload = load_fixture()
        for row in rows(payload):
            margins = dict(row["margins"])
            losing = [move for move, margin in margins.items() if margin <= 0]
            assert losing, "every move wins, so there is nothing to get wrong"
            tempted = margins[row["tempting"]] <= 0
            assert tempted or row["greedy_falls"], "the losing moves are not tempting"

    def test_every_puzzle_sits_inside_its_stage_s_band(self) -> None:
        payload = load_fixture()
        bands = {stage["stage"]: stage["empties"] for stage in payload["stages"]}
        for row in rows(payload):
            state = state_of_row(row, payload["board_size"])
            low, high = bands[row["stage"]]
            assert row["empties"] == empties(state)
            assert low <= row["empties"] <= high

    def test_the_file_is_already_in_presentation_order(self) -> None:
        """This is the test that keeps it a progression rather than a sorted pile.

        The app reads the file top to bottom. If the generator ever stops
        ordering it, the curriculum silently becomes a shuffle while every other
        test here still passes.
        """
        payload = load_fixture()
        listed = [row["stage"] for row in rows(payload)]
        assert listed == sorted(listed)

        for stage in payload["stages"]:
            within = [row["difficulty"] for row in rows(payload) if row["stage"] == stage["stage"]]
            assert within == sorted(within), f"stage {stage['stage']} is out of order"

    def test_stage_metadata_matches_the_curriculum_in_code(self) -> None:
        payload = load_fixture()
        by_number = {stage.number: stage for stage in STAGES}
        for listed in payload["stages"]:
            stage = by_number[listed["stage"]]
            assert listed["empties"] == [stage.low, stage.high]
            assert listed["title"] == stage.title


class TestShippedAnswers:
    """Re-solving the shipped puzzles. The check a wrong file cannot survive."""

    def _verify(self, row: dict, board_size: int) -> None:
        state = state_of_row(row, board_size)
        solution = solve_root(state)

        assert dict(row["margins"]) == solution.margins
        assert row["best"] == solution.best
        assert row["difficulty"] >= 0

        # And the stored line of play really reaches the stored score, so the
        # replay a player is shown after a correct answer is not a decoration.
        played = state
        for action in row["pv"]:
            played = rules.apply(played, action)
        assert rules.is_terminal(played)
        black, white = scoring.disc_counts(played)
        mine, theirs = (black, white) if state.to_move is Player.BLACK else (white, black)
        assert mine - theirs == row["best"]

    def test_the_small_stages_are_exactly_what_the_solver_says(self) -> None:
        payload = load_fixture()
        checked = [row for row in rows(payload) if row["empties"] <= FAST_LANE_EMPTIES]
        assert checked, "no puzzle small enough for the fast lane"
        for row in checked:
            self._verify(row, payload["board_size"])

    @pytest.mark.slow
    @pytest.mark.timeout(1800)
    def test_every_shipped_puzzle_is_exactly_what_the_solver_says(self) -> None:
        payload = load_fixture()
        for row in rows(payload):
            self._verify(row, payload["board_size"])


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _five_empty_position() -> State:
    """A position that ends before the board is full, played out by random moves.

    Built rather than written down, because a hand-typed board is one transposed
    row away from testing nothing. The requirement is a game whose perfect play
    leaves empty squares -- that is what makes the two scoring conventions
    disagree, which is what these tests are about.
    """
    rng = np.random.default_rng(7)
    for _ in range(500):
        state = rules.initial_state(8)
        while not rules.is_terminal(state) and empties(state) > 5:
            legal = rules.legal_actions(state)
            state = rules.apply(state, int(legal[rng.integers(0, len(legal))]))
        if rules.is_terminal(state) or empties(state) != 5:
            continue
        skip = pass_action(8)
        if len([a for a in rules.legal_actions(state) if a != skip]) < 2:
            continue
        if solve_root(state).margins != solve_root(state, empties_to_winner=True).margins:
            return state
    raise AssertionError("no position found where the two scoring conventions differ")


def _puzzle_stub(state: State, edax: RootSolution) -> Puzzle:
    """A puzzle built from a solve rather than from mining.

    ``write_obf`` reads two of these fields. Mining a real puzzle here would cost
    a minute and a loaded network to test a string format.
    """
    solution = solve_root(state)
    return Puzzle(
        stage=1,
        state=state,
        empties=empties(state),
        margins=dict(solution.margins),
        best=solution.best,
        best_moves=solution.best_moves,
        winning_moves=solution.winning_moves,
        principal_variation=solution.principal_variation,
        edax_margins=dict(edax.margins),
        tempting_move=solution.best_moves[0],
        tempting_margin=solution.best,
        trap_mass=0.0,
        greedy_falls=False,
        difficulty=0,
        nodes=solution.nodes,
    )


def test_square_names_round_trip_through_the_problem_format() -> None:
    """``19`` is D3 both ways, or every score in the file is against a wrong move."""
    for action in range(64):
        assert square_index(square_name(action)) == action
